### ISSUE TITLE
Dark mode toggle

### ISSUE THREAD

**Issue by aliou** [aliou/aliou.github.io#28]

**Comment by Dorson** [comment]
At least one dark mode set of colors would be good.

Recently, I coded the Dark Mode switch in CSS and basic Java Script.

In my version of the dark mode, we can have multiple color themes in one CSS file. Then set or remember color settings with one short JS function without logins.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:

**Comment by aliou** [comment]
Thanks. I already most of it already figured out as I already set the mode depending on the system using the `prefers-color-scheme` media query, I just need to add the toggle.

**Comment by Dorson** [comment]
CSS color variables inside of 

**:root.bright-color-reset-css-class**

Would reset the user setting. Did that in my solution to allow bright colors, if the user has dark mode preference on, but wants to have bright colors in the moment.
